/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStrapiRouteImport } from './routes/demo/strapi'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoClerkRouteImport } from './routes/demo/clerk'
import { Route as DemoApolloClientRouteImport } from './routes/demo.apollo-client'
import { Route as DemoStrapiArticleIdRouteImport } from './routes/demo/strapi.$articleId'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'

const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStrapiRoute = DemoStrapiRouteImport.update({
  id: '/demo/strapi',
  path: '/demo/strapi',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApolloClientRoute = DemoApolloClientRouteImport.update({
  id: '/demo/apollo-client',
  path: '/demo/apollo-client',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStrapiArticleIdRoute = DemoStrapiArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => DemoStrapiRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/demo/apollo-client': typeof DemoApolloClientRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/strapi': typeof DemoStrapiRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/strapi/$articleId': typeof DemoStrapiArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/demo/apollo-client': typeof DemoApolloClientRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/strapi': typeof DemoStrapiRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/strapi/$articleId': typeof DemoStrapiArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/demo/apollo-client': typeof DemoApolloClientRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/strapi': typeof DemoStrapiRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/strapi/$articleId': typeof DemoStrapiArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/demo/apollo-client'
    | '/demo/clerk'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/store'
    | '/demo/strapi'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/webhooks/stripe'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/strapi/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/demo/apollo-client'
    | '/demo/clerk'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/store'
    | '/demo/strapi'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/webhooks/stripe'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/strapi/$articleId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/demo/apollo-client'
    | '/demo/clerk'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/store'
    | '/demo/strapi'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/webhooks/stripe'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/strapi/$articleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  DemoApolloClientRoute: typeof DemoApolloClientRoute
  DemoClerkRoute: typeof DemoClerkRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoStrapiRoute: typeof DemoStrapiRouteWithChildren
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/strapi': {
      id: '/demo/strapi'
      path: '/demo/strapi'
      fullPath: '/demo/strapi'
      preLoaderRoute: typeof DemoStrapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/apollo-client': {
      id: '/demo/apollo-client'
      path: '/demo/apollo-client'
      fullPath: '/demo/apollo-client'
      preLoaderRoute: typeof DemoApolloClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/strapi/$articleId': {
      id: '/demo/strapi/$articleId'
      path: '/$articleId'
      fullPath: '/demo/strapi/$articleId'
      preLoaderRoute: typeof DemoStrapiArticleIdRouteImport
      parentRoute: typeof DemoStrapiRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DemoStrapiRouteChildren {
  DemoStrapiArticleIdRoute: typeof DemoStrapiArticleIdRoute
}

const DemoStrapiRouteChildren: DemoStrapiRouteChildren = {
  DemoStrapiArticleIdRoute: DemoStrapiArticleIdRoute,
}

const DemoStrapiRouteWithChildren = DemoStrapiRoute._addFileChildren(
  DemoStrapiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  DemoApolloClientRoute: DemoApolloClientRoute,
  DemoClerkRoute: DemoClerkRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoStrapiRoute: DemoStrapiRouteWithChildren,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
